### ISSUE TITLE
Waiting for 1 bucket(s) to finish.. is it forever? not exactly.

### ISSUE THREAD

**Issue by TwoPointInfinity** [BRForgers/DisFabric#44] opened 2021-12-04 18:11 UTC
When stopping my server the server take awhile to stop.. sometimes. Sometimes it shuts down quickly and other times it can take ages, long enough i've decided to break script and end the server manually. 
https://gyazo.com/e4cf8f603ab956e62dd813f60851a091
usually it will just sit here like this for a long time. I often do wait for it to finish and it can take a few minutes but other times, like while making this report, it has been like this upwards of 10 minutes. Without disfabric this doesnt happen, i havent tested this with ONLY disfabric so im not sure if its a conflict. Let me know what information i can provide to help out with this in-case it cant be replicated.

**Comment by Xujiayao** [comment] 2021-12-13 09:21
Are you using `/stop` command in the terminal, or `!console stop` in Discord?

**Comment by TwoPointInfinity** [comment] 2021-12-13 09:40
I usually use /stop in game or stop in console but the discord command also yields the slow stopping of the server.

**Comment by Xujiayao** [comment] 2021-12-13 11:22
Hmmm

For me
Without mod is ~0.5s
With mod, stop in console is ~5s
With mod, stop in discord is like forever

Yours same?

**Comment by TwoPointInfinity** [comment] 2021-12-13 14:07
Stop in discord is almost always forever and sometimes stop in game js like forever. Its a bummer when I'm not around and my friend wants to restart the server from in game.

**Comment by Xujiayao** [comment] 2021-12-13 14:49
I solved the problem with this commit: https://github.com/Xujiayao/MCDiscordChat/commit/b6b089d46ac93670dcfb00d239db2d9caa5745d5

Maybe try this and test it out? You may try sending `!stop` and `!console stop`.
https://www.curseforge.com/minecraft/mc-mods/mcdiscordchat

**Comment by allanf181** [comment] 2021-12-13 17:54
Duplicate of #16

**Closed by allanf181** 2021-12-13 17:54 UTC
Labels: duplicate
